export declare function loadConfig(file: string): any;
export declare const packageRoot: string;
export declare const packageJSON: any;
export declare const boilerplateRoot: string;
export declare const boilerplateJSON: any;
export declare const contentRootFolder: string;
export declare const contentRoot: string;
export declare const configFile: string;
export declare const configFileTypescriptNode: string;
export declare const configFileTypescriptReact: string;
export declare const configFileWebpack: string;
export declare const configFileBabel: string;
export declare const configFilePostCSS: string;
export declare const buildFolder = "build";
export declare const staticFolder = "static";
export declare const srcFolder = "src";
export declare const reportFolder = "report";
export declare const loadedStaticFolder = "loaded";
export declare const logoFolder = "logo";
export declare const buildDir: (mode: string) => string;
export declare const staticDir: string;
export declare const srcDir: string;
export declare const reportDir: (mode: string) => string;
export declare const loadedStaticDir: string;
export declare const logoDir: string;
